### ISSUE TITLE
api文档不清晰，求帮助

### ISSUE THREAD

**Issue by 5454267364** [GetuiLaboratory/getui-gcsdk-ios-cocoapods#1]
个数ios端  “setSmartReporting”  怎么设置？为什么这样设置是不行的？以下几个都用不了，但是又不会报错，而且会导致sdk启动不了。。
BOOL enableSmartReporting=args[@"enableSmartReporting"];
[[GTCountSDK sharedInstance] setSmartReporting:enableSmartReporting];

NSUInteger maxBatchReportCount=args[@"maxBatchReportCount"];
[[GTCountSDK sharedInstance] setMinBatchReportNumber:maxBatchReportCount];

还有安卓端可以获取渠道和是否开发者模式，ios端是否有这个接口呢？

**Comment by aklee** [comment]
请参考官网文档中心：https://docs.getui.com/geshu/start/ios/
